# Generated by Django 3.0.7 on 2020-06-07 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_auto_20200607_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.DecimalField(decimal_places=2, max_digits=4)),
                ('usability', models.DecimalField(decimal_places=2, max_digits=4)),
                ('content', models.DecimalField(decimal_places=2, max_digits=4)),
                ('average', models.DecimalField(decimal_places=2, max_digits=4)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='award.Profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='award.Project')),
            ],
        ),
    ]
